name: Build Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Generate resources
      run: |
        dart run flutter_launcher_icons:main || true
        dart run flutter_native_splash:create || true
        flutter pub run build_runner build --delete-conflicting-outputs || true
        
    - name: Build Web
      run: flutter build web --release --web-renderer html
      
    - name: Get build info
      id: build_info
      run: |
        VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
        TIMESTAMP=$(date +'%Y%m%d_%H%M%S')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT
        
    - name: Archive Web Build
      run: |
        cd build/web
        tar -czf ../../baozi_comic_web_v${{ steps.build_info.outputs.VERSION }}_${{ steps.build_info.outputs.TIMESTAMP }}.tar.gz .
        
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: baozi_comic_web_v${{ steps.build_info.outputs.VERSION }}_${{ steps.build_info.outputs.TIMESTAMP }}
        path: baozi_comic_web_v${{ steps.build_info.outputs.VERSION }}_${{ steps.build_info.outputs.TIMESTAMP }}.tar.gz
        retention-days: 30
        
    # Optional: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
        cname: # 如果有自定义域名，在这里设置
